'use strict';
const cheerio=require('cheerio');const {clean,fold,parseDate}=require('./core.cjs');
const profile='https://contrataciondelestado.es/wps/poc?uri=deeplink%3AperfilContratante&idBp=RXFb51aFpEHmnwcj%2BxbdTg%3D%3D';
function parseAgencyList(html){const $=cheerio.load(html);return $('tr').map((i,e)=>{const el=$(e),url=el.find('a[href*="detalle_licitacion"]').attr('href');if(!url)return null;const sourceStatus=clean(el.find('.tdEstado').text()),title=clean(el.find('.tdTipoContratoLicOC').text()),date=clean(el.find('.tdFecha').text());return {noticeId:clean(el.find('.tdExpediente span').text()),procedureId:clean(el.find('.tdExpediente span').text()),sourceUrl:url,title,description:title,buyer:'Dirección de la Agencia Espacial Española',sourceStatus,noticeType:/adjudicad|resuelt/i.test(sourceStatus)?'award':/anuncio previo/i.test(sourceStatus)?'planning':'tender',deadlineRaw:/Present\. Oferta/.test(date)?date.match(/\d{2}\/\d{2}\/\d{4}/)?.[0]||'':'',publicationDate:'',noticeVerified:true,value:clean(el.find('.tdImporte').text()),currency:'EUR'};}).get();}
async function aee(ctx){const {chromium}=require('playwright-core'),browser=await chromium.launch(process.env.SCRAPER_BROWSER_PATH?{headless:true,executablePath:process.env.SCRAPER_BROWSER_PATH}:{headless:true,channel:'msedge'});try{const page=await browser.newPage();await page.goto(profile,{waitUntil:'networkidle',timeout:ctx.options.timeout});ctx.recordRequest();ctx.saveRendered(profile,await page.content());await page.locator('input[id$="linkPrepLic"]').click();await page.waitForLoadState('networkidle');let last='';for(let n=1;n<=ctx.options.webPages&&ctx.canFetch();n++){
 const html=await page.content(),rows=parseAgencyList(html),ids=rows.map(r=>r.noticeId).join('|');if(!rows.length)throw Error('AEE profile has no recognized tender rows');if(ids===last)throw Error('AEE pagination repeated');last=ids;ctx.recordRequest();const raw=ctx.saveRendered(profile+'&collectorPage='+n,html);for(const r of rows)ctx.emit(r,raw);
 const next=page.locator('input[id$="siguienteLink"]');if(!await next.count()||!await next.isEnabled())break;if(n===ctx.options.webPages){ctx.gap('AEE page budget reached');break;}await next.click();await page.waitForLoadState('networkidle');await page.waitForTimeout(ctx.options.delay);
 }}finally{await browser.close();}ctx.gap('AEE profile listings have some date-only deadlines and omit publication dates. Retained as undated review records; archive membership does not establish 2020-onward completeness.');}
module.exports={aee,parseAgencyList};
