const test=require('node:test'),assert=require('node:assert/strict');
const root=process.env.NATIONAL_ROOT||require('node:path').join(__dirname,'..');
const {dateWindows,parseGreek,parseRomania,parseHilma}=require(root+'/native-portals.cjs');
const {parsePortugal,usDate,parseSlovakia,swedishNotices,parseSwedishAward}=require(root+'/native-portals-final.cjs');
const {classify,normalize,statusOf}=require(root+'/core.cjs');
test('Greek history windows include every date exactly once, including leap day',()=>{const w=dateWindows('2020-01-01','2026-10-05');assert.equal(w[0].to,'2026-10-05');assert.equal(w.at(-1).from,'2020-01-01');for(let i=0;i<w.length;i++){assert.ok((Date.parse(w[i].to)-Date.parse(w[i].from))/86400000<=179);if(i)assert.equal(Date.parse(w[i-1].from)-Date.parse(w[i].to),86400000);}});
test('Greek time intervals are not space procurement',()=>{assert.equal(classify('ΥΠΗΡΕΣΙΕΣ ΚΑΘΑΡΙΟΤΗΤΑΣ ΓΙΑ ΔΙΑΣΤΗΜΑ 24 ΜΗΝΩΝ','').relevance,'unrelated');assert.equal(classify('ΔΟΡΥΦΟΡΙΚΩΝ ΕΠΙΚΟΙΝΩΝΙΩΝ','').relevance,'space');assert.equal(classify('ΔΙΑΣΤΗΜΙΚΗ ΤΕΧΝΟΛΟΓΙΑ','').relevance,'space');});
test('Named gallery and charging satellites need review',()=>{assert.equal(classify('Galéria Satelit - Oprava stien','').relevance,'possible_space');assert.equal(classify('ELB Levering af ladestandere','ladepunkter udført som satellitter').relevance,'possible_space');assert.equal(classify('Satelitný prenos z hydrologických staníc','').relevance,'space');});
test('Portal-local dates do not inherit US or UTC interpretation',()=>{assert.equal(usDate('12/22/2025, 10:00 AM'),'2025-12-22T10:00:00');assert.equal(usDate('6/22/2026, 12:10 PM'),'2026-06-22T12:10:00');assert.equal(usDate('6/22/2026, 12:10 AM'),'2026-06-22T00:10:00');});
test('BASE contracts remain awards regardless of a future date',()=>{const x=parsePortugal({id:1,publicationDate:'29-09-2026',objectBriefDescription:'GNSS equipment'});assert.equal(x.publicationDate,'2026-09-29');assert.equal(statusOf({...x,deadlineRaw:'2027-01-01'},new Date('2026-10-05'))[0],'awarded');});
test('Document-only keyword hits are explicitly review candidates',()=>{const x=normalize({title:'Kopierings- och tryckeritjänster',description:'satellit',noticeType:'tender',noticeVerified:true,deadlineRaw:'2027-01-01',relevanceReviewReason:'Document-only match'},{id:'SE-eavrop',country:'SE',timeZone:'Europe/Stockholm'},'raw/test');assert.equal(x.relevance,'possible_space');assert.match(x.reviewEvidence,/Document-only/);});
test('Award notices and cancellations cannot be open',()=>{const x=parseGreek({referenceNumber:'1',title:'GNSS',auctionRefNo:['award'],finalSubmissionDate:'2027-01-01'});assert.equal(statusOf(x)[0],'awarded');assert.equal(statusOf({...x,sourceStatus:'cancelled'})[0],'cancelled');});
test('Embedded JSON parser reads data without evaluating script',()=>{const notices=swedishNotices(`eavropReact.notices.mountComponent(foo, 'bar', {"notices":[{"Object":{"Title":"a } bracket"},"NoticeTypeString":"CAN"}]}, other);`);assert.equal(notices[0].Object.Title,'a } bracket');assert.equal(parseSwedishAward(notices[0]).noticeType,'award');assert.throws(()=>swedishNotices('no notices'));});


test('Czech spaced calendar dates retain the future submission deadline',()=>{const {parseCzech}=require(root+'/native-portals.cjs');const html='<div class="gov-grid-tile"><h3>PROCUREMENT PROCEDURE NAME</h3><p>Satellite software</p></div><div class="gov-grid-tile"><h3>DATE OF PUBLICATION ON PROFILE</h3><p>14. 09. 2026 22:07</p></div><div class="gov-grid-tile"><h3>DEADLINE FOR SUBMITTING TENDERS</h3><p>12. 10. 2026 10:00</p></div>';const x=parseCzech(html,'https://nen.nipez.cz/example');assert.equal(x.publicationDate,'2026-09-14');assert.equal(x.deadlineRaw,'2026-10-12T10:00');});
