'use strict';
const fs=require('node:fs'),path=require('node:path'),cheerio=require('cheerio');
const {chromium}=require('playwright-core');const {clean,hash,parseDate}=require('./core.cjs');
const commonTerms=['satellite','GNSS','Copernicus','Galileo','EGNOS','spacecraft','earth observation','remote sensing','CubeSat','SATCOM'];
const date=x=>String(x||'').slice(0,10),join=a=>(a||[]).map(x=>x.text||'').filter(Boolean).join(' | ');
function save(ctx,url,payload,body){const name=ctx.source.id+'-'+hash(url+JSON.stringify(payload)).slice(0,20)+'.json';fs.writeFileSync(path.join(ctx.rawDir,name),body,'utf8');return 'raw/'+name;}
async function publicSession(ctx,url,match,trigger,method='POST'){
 const browser=await chromium.launch(process.env.SCRAPER_BROWSER_PATH?{headless:true,executablePath:process.env.SCRAPER_BROWSER_PATH}:{headless:true,channel:'msedge'});
 try{const page=await browser.newPage();let captured;page.on('request',r=>{if(r.url().includes(match)&&r.method()===method)captured=r;});
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:ctx.options.timeout});if(trigger)await trigger(page);
 for(let i=0;i<60&&!captured;i++)await page.waitForTimeout(500);
 if(!captured)throw Error('Public search request not observed: '+match);
 const headers=await captured.allHeaders();for(const k of Object.keys(headers))if(k.startsWith(':')||['content-length','host','cookie'].includes(k))delete headers[k];
 return {browser,page,template:method==='POST'?captured.postDataJSON():{},get:async url=>{if(!ctx.canFetch())throw Error('Request budget reached');await new Promise(r=>setTimeout(r,ctx.options.delay));ctx.recordRequest();const r=await page.context().request.get(url,{headers,timeout:ctx.options.timeout});if(!r.ok())throw Error('Public search HTTP '+r.status());const body=await r.text();return {body,rawFile:save(ctx,url,null,body)};},post:async payload=>{
  if(!ctx.canFetch())throw Error('Request budget reached');await new Promise(r=>setTimeout(r,ctx.options.delay));ctx.recordRequest();
  const response=await page.context().request.post(captured.url(),{headers,data:payload,timeout:ctx.options.timeout});
  if(!response.ok())throw Error('Public search HTTP '+response.status());const body=await response.text();return {data:JSON.parse(body),rawFile:save(ctx,captured.url(),payload,body)};
 }};}catch(e){await browser.close();throw e;}
}
function parseHilma(x){const title=[x.titleEn,x.titleFi,x.titleSv,x.titleOther].filter(Boolean).join(' | '),description=[x.descriptionEn,x.descriptionFi,x.descriptionSv,x.descriptionOther].filter(Boolean).join('\n');
 const kind=x.isPlan||/PriorInformation|Plan/.test(x.mainType)?'planning':/Award|Modification/.test(x.mainType)?'award':/ContractNotices|NationalNotices/.test(x.mainType)?'tender':'unknown';
 return {noticeId:x.id,procedureId:String(x.procedureId||x.oldProcurementProjectId||x.id),sourceUrl:x.isEForms?'https://www.hankintailmoitukset.fi/en/public/procedure/'+x.procedureId+'/enotice/'+x.noticeId:'https://www.hankintailmoitukset.fi/en/public/procurement/'+x.oldProcurementProjectId+'/notice/'+x.noticeId+'/details',title,description,buyer:x.organisationNameEn||x.organisationNameFi||x.organisationNameSv||x.organisationNameOther,publicationDate:date(x.datePublished),sourceUpdated:x.dateModified,deadlineRaw:x.deadline||'',noticeType:kind,sourceStatus:x.mainType,noticeVerified:true,cpv:x.cpvCodes,value:x.estimatedValue,currency:x.currency};
}
async function hilma(ctx){const seen=new Set();for(const term of [...commonTerms,'satelliitti','avaruus','kaukokartoitus','rymd','jordobservation']){
 let skip=0;while(ctx.canFetch()){const u=new URL('https://www.hankintailmoitukset.fi/search/eformnotices');u.search=new URLSearchParams({search:term.includes(' ')?'"'+term+'"':term+'*',queryType:'full',searchMode:'any','$top':'100','$skip':String(skip),'$orderby':'datePublished desc','$count':'true','$filter':`datePublished ge ${ctx.options.from}T00:00:00Z and datePublished le ${ctx.options.to}T23:59:59Z`});
 const {body,rawFile}=await ctx.get(u.href),d=JSON.parse(body);if(!Array.isArray(d.value)||!Number.isFinite(d['@odata.count']))throw Error('Unrecognized HILMA search schema');for(const x of d.value){if(seen.has(x.id))continue;seen.add(x.id);ctx.emit(parseHilma(x),rawFile);}skip+=d.value.length;if(skip>=d['@odata.count'])break;if(!d.value.length)throw Error('HILMA pagination stopped early');}
 if(!ctx.canFetch()){ctx.gap('HILMA request budget reached');break;}}
 ctx.gap('Public multilingual keyword search, including closed notices; unindexed archives and notices lacking searched terms remain outside coverage.');
}
function parseEstonia(x){const status=String(x.procurementStatus),closed=['13','19','31'].includes(status)?'awarded':['91','92'].includes(status)?'cancelled':['12','15','21'].includes(status)?'closed':x.isSuspended?'suspended':status;
 return {noticeId:String(x.procurementId),procedureId:String(x.procurementId),sourceUrl:'https://riigihanked.riik.ee/rhr-web/#/procurement/'+x.procurementId+'/general-info',title:x.procurementName,description:x.shortDescription||'',buyer:x.contractingAuthorityName,publicationDate:date(x.procProcessRevealDate),deadlineRaw:x.procProcessSubmitDate||'',noticeType:['01','02','03','04','16'].includes(status)?'planning':closed==='awarded'?'award':'tender',sourceStatus:closed,noticeVerified:!x.isSuspended,cpv:x.mainCpvName||''};
}
async function estonia(ctx){const s=await publicSession(ctx,'https://riigihanked.riik.ee/rhr-web/#/','search/procurements-quick',async p=>{const box=p.locator('input[placeholder]').first();await box.fill('satelliit');await box.press('Enter');});const seen=new Set();try{
 for(const term of [...commonTerms,'satelliit','kosmos','kaugseire','maavaatlus']){if(!ctx.canFetch()){ctx.gap('Estonia request budget reached');break;}const payload={...s.template,filter:{referenceNumber:term,procurementName:term,procurementContractingAuthorityName:term,coContractingAuthorityName:term}},r=await s.post(payload);if(!Array.isArray(r.data))throw Error('Unrecognized Estonian search schema');if(r.data.length>=500)ctx.gap('Estonian quick-search may cap results for '+term);for(const x of r.data){if(seen.has(x.procurementId))continue;seen.add(x.procurementId);ctx.emit(parseEstonia(x),r.rawFile);}}
 }finally{await s.browser.close();}ctx.gap('National quick-search matches titles and buyers; description-only matches and unindexed history are not exhaustive.');}
function parseBelgium(x){const n=Number(x.noticeSubType),kind=n>=25&&n<=38?'award':n>=1&&n<=9?'planning':n>=10&&n<=24?'tender':'unknown';
 return {noticeId:x.publicationWorkspaceId,procedureId:x.procedureId||x.publicationWorkspaceId,sourceUrl:'https://www.publicprocurement.be/publication-workspaces/'+x.publicationWorkspaceId,title:join(x.dossier?.titles),description:join(x.dossier?.descriptions)+'\n'+(x.lots||[]).map(l=>join(l.titles)+' '+join(l.descriptions)).join('\n'),buyer:join(x.organisation?.organisationNames),publicationDate:date(x.publicationDate),sourceUpdated:(x.publishedAt||[]).sort().at(-1)||x.publicationDate,deadlineRaw:x.vaultSubmissionDeadline||'',noticeType:kind,sourceStatus:kind==='award'?'awarded':x.publicationType,noticeVerified:true,cpv:[x.cpvMainCode?.code,...(x.cpvAdditionalCodes||[]).map(c=>c.code)].filter(Boolean).join(' | ')};
}
async function belgium(ctx){const s=await publicSession(ctx,'https://www.publicprocurement.be/','search/publications',async p=>{const b=p.locator('input[placeholder]').first();await b.fill('satellite');await b.press('Enter');});const seen=new Set();try{for(const term of [...commonTerms,'satelliet','ruimtevaart','télédétection','spatial','aardobservatie']){let page=1,total=0;while(ctx.canFetch()){const r=await s.post({...s.template,terms:term,page,pageSize:25});if(!Array.isArray(r.data.publications))throw Error('Unrecognized Belgian search schema');for(const x of r.data.publications){if(seen.has(x.publicationWorkspaceId))continue;seen.add(x.publicationWorkspaceId);ctx.emit(parseBelgium(x),r.rawFile);}total+=r.data.publications.length;if(total>=r.data.totalCount)break;if(!r.data.publications.length)throw Error('Belgian pagination stopped early');page++;}if(!ctx.canFetch()){ctx.gap('Belgian page budget reached');break;}}}finally{await s.browser.close();}ctx.gap('Current federal search platform; legacy pre-migration publications and unindexed local portals may be missing.');}
function parseRomania(x){const state=x.sysProcedureState?.text||'',status=/anulat/i.test(state)?'cancelled':/atribuit/i.test(state)?'awarded':state;
 return {noticeId:String(x.noticeId),procedureId:String(x.procedureId),sourceUrl:'https://www.e-licitatie.ro/pub/notices/c-notice/v2/view/'+x.cNoticeId,title:x.contractTitle,description:x.contractTitle,buyer:x.contractingAuthorityNameAndFN,publicationDate:date(x.noticeStateDate),sourceUpdated:x.noticeStateDate,deadlineRaw:x.minTenderReceiptDeadline||'',noticeType:status==='awarded'?'award':'tender',sourceStatus:status,noticeVerified:true,cpv:x.cpvCodeAndName,value:x.estimatedValueRon,currency:'RON'};
}
async function romania(ctx){const s=await publicSession(ctx,'https://www.e-licitatie.ro/pub/notices/contract-notices/list/0/0','GetCNoticeList');const seen=new Set();try{for(const term of [...commonTerms,'satelit','spațial','teledetecție','observarea']){let pageIndex=0,total=0;while(ctx.canFetch()){const r=await s.post({...s.template,contractName:term,startPublicationDate:ctx.options.from+'T00:00:00',endPublicationDate:ctx.options.to+'T23:59:59',pageSize:100,pageIndex});if(!Array.isArray(r.data.items))throw Error('Unrecognized Romanian search schema');if(r.data.searchTooLong)ctx.gap('Romanian query capped or timed out: '+term);for(const x of r.data.items){if(seen.has(x.noticeId))continue;seen.add(x.noticeId);ctx.emit(parseRomania(x),r.rawFile);}total+=r.data.items.length;if(total>=r.data.total)break;if(!r.data.items.length)throw Error('Romanian pagination stopped early');pageIndex++;}if(!ctx.canFetch()){ctx.gap('Romanian request budget reached');break;}}}finally{await s.browser.close();}ctx.gap('SEAP initiation-notice title search with current procedure status; separate direct-purchase catalogue and description-only matches remain outside this adapter.');}
async function post(ctx,url,payload){if(ctx.options.rawCacheDir){const f=path.join(ctx.options.rawCacheDir,ctx.source.id+'-'+hash(url+JSON.stringify(payload)).slice(0,20)+'.json');if(fs.existsSync(f)){const body=fs.readFileSync(f,'utf8'),d=JSON.parse(body);return {data:d.message==='No notices found for the given criteria'?{content:[],last:true,totalPages:0}:d,rawFile:save(ctx,url,payload,body)};}}if(!ctx.canFetch())throw Error('Request budget reached');await new Promise(r=>setTimeout(r,ctx.options.delay));ctx.recordRequest();const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(ctx.options.timeout)});const body=await r.text();if(!r.ok){if(r.status===404&&url.startsWith('https://cerpp.eprocurement.gov.gr/khmdhs-opendata/notice?')&&JSON.parse(body).message==='No notices found for the given criteria')return {data:{content:[],last:true,totalPages:0},rawFile:save(ctx,url,payload,body)};throw Error('Public API HTTP '+r.status);}return {data:JSON.parse(body),rawFile:save(ctx,url,payload,body)};}
const euroDate=x=>{const m=String(x||'').replace(/([./])\s+/g,'$1').match(/(\d{2})[/.\-](\d{2})[/.\-](\d{4})(?:,?\s+(\d{2}:\d{2}))?/);return m?m[3]+'-'+m[2]+'-'+m[1]+(m[4]?'T'+m[4]:''):'';};
function parseCzech(html,url){const $=cheerio.load(html),pairs=new Map();$('.gov-grid-tile').each((i,e)=>{pairs.set(clean($(e).find('h3').text()).toLowerCase(),clean($(e).find('p').text()));});const get=k=>pairs.get(k)||'',title=get('procurement procedure name');if(!title)throw Error('Unrecognized NEN detail');const status=get('current status of the procurement procedure'),kind=/awarded|termination of performance/i.test(status)?'award':'tender';return {noticeId:get('nen system number'),procedureId:get('nen system number'),sourceUrl:url,title,description:get('subject-matter description'),buyer:get('contracting authority'),publicationDate:date(euroDate(get('date of publication on profile'))),deadlineRaw:euroDate(get('deadline for submitting tenders')),noticeType:kind,sourceStatus:/cancel/i.test(status)?'cancelled':kind==='award'?'awarded':status,noticeVerified:true,cpv:get('code from the cpv code list')};}
async function czech(ctx){const seen=new Set();for(const term of [...commonTerms,'satelit','družic','kosmick','vesmír','dálkový průzkum']){if(!ctx.canFetch()){ctx.gap('NEN request budget reached');break;}const url='https://nen.nipez.cz/en/verejne-zakazky/p:vz:query='+encodeURIComponent(term),r=await ctx.get(url),$=cheerio.load(r.body),links=[...new Set($('a[href*="/detail-zakazky/"]').map((i,e)=>new URL($(e).attr('href'),url).href).get())];
 for(const link of links){if(seen.has(link))continue;seen.add(link);if(!ctx.canFetch()){ctx.gap('NEN detail request budget reached');break;}try{const d=await ctx.get(link);ctx.emit(parseCzech(d.body,link),d.rawFile);}catch(e){ctx.gap(link+': '+e.message);}}
 if(links.length>=100)ctx.gap('NEN search returned at least 100 links; confirm search-result limit for '+term);}
 ctx.gap('NEN public keyword searches; other Czech contracting platforms and records absent from NEN remain outside coverage.');}
function parseDanish(x){const d=x.dataEn||x.dataDa,kind=d.formulartypeKode==='result'?'award':d.formulartypeKode==='planning'?'planning':d.formulartypeKode==='competition'?'tender':'unknown';return {noticeId:x.noticeId+'|'+x.noticeVersion,sourceUrl:'https://udbud.dk/detaljevisning?'+new URLSearchParams({noticeId:x.noticeId,noticeVersion:x.noticeVersion,noticePublicationNumber:x.noticePublicationNumber||''}),title:d.titel,description:d.beskrivelse,buyer:d.ordregiver,publicationDate:date(euroDate(d.publiceringsdato)),deadlineRaw:(d.tidsfrister||[]).slice().sort()[0]||'',noticeType:kind,sourceStatus:kind==='award'?'awarded':d.formulartypeKode,noticeVerified:true,cpv:d.cpvKode,value:d.anslaaetVaerdi,currency:d.anslaaetVaerdiValuta};}
async function denmark(ctx){const seen=new Set();for(const term of [...commonTerms,'satellit','rumfart','jordobservation','fjernmåling']){let page=1,count=0;while(ctx.canFetch()){const r=await post(ctx,'https://udbud.dk/soegning/public/soegeresultat',{fritekstQuery:term,pagineringDto:{aktuelSide:page,maksElementer:100,sorteringFelt:'PUBLIKATION_DATO',retning:'Desc'},filterDto:{formularType:[],opgaveType:[],procedureType:[],smvVenligType:[]},udbudStatusFilter:'ALLE'});const rows=r.data.resultatElementDtoList;if(!Array.isArray(rows))throw Error('Unrecognized Danish schema');for(const x of rows){const id=x.noticeId+'|'+x.noticeVersion;if(seen.has(id))continue;seen.add(id);ctx.emit(parseDanish(x),r.rawFile);}count+=rows.length;if(count>=r.data.totaltAntalResultater)break;if(!rows.length)throw Error('Danish pagination stopped early');page++;}if(!ctx.canFetch()){ctx.gap('Danish request budget reached');break;}}ctx.gap('Current Danish search including historical notices; separate 2022–2024 below-threshold archive not yet enumerated. Portal may also publish EU institution notices; buyer provenance retained.');}
const arrayDate=x=>Array.isArray(x)?x.slice(0,3).map((n,i)=>i?String(n).padStart(2,'0'):n).join('-')+(x.length>=5?'T'+String(x[3]).padStart(2,'0')+':'+String(x[4]).padStart(2,'0'):''):'';
function parseHungary(x){const state=x.eljarasSzakasz?.ertekEn||'',n=x.legfrissebbHirdetmeny,kind=/award|contracting and performance/i.test((n?.hirdetmenyTipus?.ertekEn||'')+' '+state)?'award':/planning|prior information/i.test(state)?'planning':'tender';return {noticeId:x.eljarasAzonosito,procedureId:x.eljarasAzonosito,sourceUrl:'https://ekr.gov.hu/eljarastar/eljaras/'+x.eljarasAzonosito,title:x.eljarasTargy,description:x.eljarasTargy,buyer:x.ajanlatkeroSzervezetNeve,publicationDate:date(arrayDate(x.meginditasDatum)),sourceUpdated:arrayDate(n?.ekrKozzetetelDatum),deadlineRaw:arrayDate(x.ajanlatteteliHatarido),noticeType:kind,sourceStatus:kind==='award'?'awarded':state,noticeVerified:true};}
async function hungary(ctx){const seen=new Set();for(const term of [...commonTerms,'műhold','űrkutatás','távérzékelés','űreszköz']){let offset=0;while(ctx.canFetch()){const u='https://ekr.gov.hu/eljarastar/api/public/kereso?'+new URLSearchParams({kifejezes:term,osszes:'true',order:'MEGINDITAS_DATUMA_DESC',offset:String(offset),limit:'100'});const r=await ctx.get(u),d=JSON.parse(r.body);if(!Array.isArray(d.eljarasTalalatok))throw Error('Unrecognized EKR schema');for(const x of d.eljarasTalalatok){if(seen.has(x.eljarasAzonosito))continue;seen.add(x.eljarasAzonosito);ctx.emit(parseHungary(x),r.rawFile);}offset+=d.eljarasTalalatok.length;if(offset>=d.totalRecords)break;if(!d.eljarasTalalatok.length)throw Error('EKR pagination stopped early');}if(!ctx.canFetch()){ctx.gap('Hungarian request budget reached');break;}}ctx.gap('EKR all-procedure keyword search; only public search summaries are extracted, with current lifecycle status.');}
function parseGreek(x){const awarded=(x.auctionRefNo||[]).length>0;return {noticeId:x.referenceNumber,procedureId:x.amendedNoticeADAM||x.referenceNumber,sourceUrl:'https://cerpp.eprocurement.gov.gr/khmdhs-opendata/notice/attachment/'+encodeURIComponent(x.referenceNumber),title:x.title,description:(x.objectDetails||[]).map(d=>d.shortDescription).filter(Boolean).join('\n'),buyer:x.organization?.value,publicationDate:date(x.submissionDate),sourceUpdated:x.lastUpdateDate||x.submissionDate,deadlineRaw:x.finalSubmissionDate||'',noticeType:awarded?'award':'tender',sourceStatus:x.cancelled?'cancelled':awarded?'awarded':'',noticeVerified:true,cpv:(x.objectDetails||[]).flatMap(d=>(d.cpvs||[]).map(c=>c.key)).join(' | '),value:x.totalCostWithoutVAT,currency:'EUR',documents:x.biddingWebsite||''};}
function dateWindows(from,to){const result=[];let end=Date.parse(to+'T00:00:00Z'),first=Date.parse(from+'T00:00:00Z');while(end>=first){const start=Math.max(first,end-179*86400000);result.push({from:new Date(start).toISOString().slice(0,10),to:new Date(end).toISOString().slice(0,10)});end=start-86400000;}return result;}
async function greece(ctx){const found=new Map();if(ctx.options.rawCacheDir)ctx.gap('Explicit raw cache reused for previously collected historical search pages.');try{for(const range of dateWindows(ctx.options.from,ctx.options.to))for(const term of [...commonTerms,'δορυφορ','διαστημικ','τηλεπισκ','γεωπαρατήρ']){let page=0;while(ctx.canFetch()){const r=await post(ctx,'https://cerpp.eprocurement.gov.gr/khmdhs-opendata/notice?page='+page,{title:term,dateFrom:range.from,dateTo:range.to}),d=r.data;if(!Array.isArray(d.content))throw Error('Unrecognized KIMDIS response');for(const x of d.content)found.set(x.referenceNumber,{x,raw:r.rawFile});if(d.last||page+1>=d.totalPages)break;if(!d.content.length)throw Error('KIMDIS pagination stopped early');page++;}if(!ctx.canFetch()){ctx.gap('Greek request budget reached');break;}}
 }finally{for(const {x,raw} of found.values()){const r=parseGreek(x),seen=new Set([x.referenceNumber]);let parent=x.amendedNoticeADAM;while(parent&&!seen.has(parent)){r.procedureId=parent;seen.add(parent);parent=found.get(parent)?.x.amendedNoticeADAM;}ctx.emit(r,raw);}}
 ctx.gap('KIMDIS public notice title search, with cancellation and linked-award flags; some invitations are addressed to selected suppliers. Unlinked awards and description-only matches require further checking.');}
module.exports={dateWindows,hilma,estonia,belgium,romania,czech,denmark,hungary,greece,parseHilma,parseEstonia,parseBelgium,parseRomania,parseCzech,parseDanish,parseHungary,parseGreek,publicSession,post,save,commonTerms};
